### PR TITLE
feat: Fedora arm64 support. 

### LINKED ISSUE #259: Fedora arm64 suppot
Recently we added support for RHEL arm64, it seems there are AMIs for Fedora arm64, so add support for Fedora arm64 should be feasible

### PR DESCRIPTION
**Pull request by adrianriobo**
Fix #259

### CODE REVIEW

**Comment by anjannath** [comment]
Tested this and an `arm64` instance is created (i tried with `--spot`) but for some reason the readiness check is always failing for both `x86_64` and `arm64` 

when i try to create a fedora instance `amd64` from the main branch the readiness check doesn't fail :/

**Comment by adrianriobo** [comment]
Ok will test again

**Comment by adrianriobo** [comment]
Tested arm64:

```
aws fedora create \
                project-name debug-fedora \
                backed-url file:///home/user/fedora \
                conn-details-output /home/user/fedora \
                arch arm64 \
                vm-types m7g.xlarge,m6g.xlarge,c7g.2xlarge \
                spot
```

And created ok:

```
...
INFO @ updating............................................................. 
INFO  +  aws:lb:LoadBalancer main-afd-lb created (163s)  
INFO  +  aws:lb:Listener main-afd-listener-22 creating (0s)  
INFO  +  command:remote:Command main-afd-readiness-cmd creating (0s)  
INFO @ updating....                               
INFO  +  aws:lb:Listener main-afd-listener-22 created (1s)  
INFO @ updating.................                  
INFO  +  command:remote:Command main-afd-readiness-cmd creating (15s) Dial 1/inf failed: retrying 
INFO @ updating..................                 
INFO  +  command:remote:Command main-afd-readiness-cmd creating (30s) Dial 2/inf failed: retrying 
INFO @ updating...................                
INFO  +  command:remote:Command main-afd-readiness-cmd creating (45s) Dial 3/inf failed: retrying 
INFO @ updating..................                 
INFO  +  command:remote:Command main-afd-readiness-cmd creating (60s) Dial 4/inf failed: retrying 
INFO @ updating..................                 
INFO  +  command:remote:Command main-afd-readiness-cmd creating (75s) Dial 5/inf failed: retrying 
INFO @ updating......                             
INFO  +  command:remote:Command main-afd-readiness-cmd creating (78s) ping 
INFO  +  command:remote:Command main-afd-readiness-cmd created (78s) ping 
INFO  +  pulumi:pulumi:Stack debug-fedora-stackFedoraBaremetal-debug-fedora created (170s)  
INFO Diagnostics:                                 
INFO   aws:ec2:Eip (eip-publicmain-afd-net0):     
INFO     warning: urn:pulumi:stackFedoraBaremetal-debug-fedora::debug-fedora::aws:ec2/eip:Eip::eip-publicmain-afd-net0 verification warning: use domain attribute instead 
INFO                                              
INFO Outputs:                                     
INFO     VPCID             : "vpc-0b7f04d0cd87b5a1b" 
INFO     main-afdHost      : "main-afd-lb-6eaad4a-c28216e023959913.elb.us-east-1.amazonaws.com" 
INFO     main-afdPrivatekey: [secret]             
INFO     main-afdUsername  : "fedora"             
INFO                                              
INFO Resources:                                   
INFO     + 18 created                             
INFO                                              
INFO Duration: 4m10s  
```

**Comment by adrianriobo** [comment]
Same on x86_64 all ok:

```bash
 aws fedora create \
                --project-name debug-fedora \
                --backed-url file:///home/user/fedora \ 
                --conn-details-output /home/user/fedora \
                --arch x86_64 \
                --vm-types m7a.xlargem6a.xlargec7a.2xlarge \ 
                --spot
```

```
...
 @ updating............................................................. 
INFO  +  aws:lb:LoadBalancer main-afd-lb created (173s)  
INFO  +  aws:lb:Listener main-afd-listener-22 creating (0s)  
INFO  +  command:remote:Command main-afd-readiness-cmd creating (0s)  
INFO @ updating....                               
INFO  +  aws:lb:Listener main-afd-listener-22 created (0.81s)  
INFO @ updating.................                  
INFO  +  command:remote:Command main-afd-readiness-cmd creating (15s) Dial 1/inf failed: retrying 
INFO @ updating..................                 
INFO  +  command:remote:Command main-afd-readiness-cmd creating (30s) Dial 2/inf failed: retrying 
INFO @ updating..................                 
INFO  +  command:remote:Command main-afd-readiness-cmd creating (45s) Dial 3/inf failed: retrying 
INFO @ updating..................                 
INFO  +  command:remote:Command main-afd-readiness-cmd creating (60s) Dial 4/inf failed: retrying 
INFO @ updating...................                
INFO  +  command:remote:Command main-afd-readiness-cmd creating (75s) Dial 5/inf failed: retrying 
INFO @ updating.......                            
INFO  +  command:remote:Command main-afd-readiness-cmd creating (80s) ping 
INFO  +  command:remote:Command main-afd-readiness-cmd created (80s) ping 
INFO  +  pulumi:pulumi:Stack debug-fedora-stackFedoraBaremetal-debug-fedora created (177s)  
INFO Diagnostics:                                 
INFO   aws:ec2:Eip (eip-publicmain-afd-net0):     
INFO     warning: urn:pulumi:stackFedoraBaremetal-debug-fedora::debug-fedora::aws:ec2/eip:Eip::eip-publicmain-afd-net0 verification warning: use domain attribute instead 
INFO                                              
INFO Outputs:                                     
INFO     VPCID             : "vpc-055401d70f6f2de6a" 
INFO     main-afdHost      : "main-afd-lb-210bd53-d2bf6c00fc60150f.elb.eu-west-1.amazonaws.com" 
INFO     main-afdPrivatekey: [secret]             
INFO     main-afdUsername  : "fedora"             
INFO                                              
INFO Resources:                                   
INFO     + 18 created                             
INFO                                              
INFO Duration: 4m18s                              
```

**Comment by adrianriobo** [comment]
@anjannath how did you exactly tested this?

**Comment by anjannath** [comment]
> @anjannath how did you exactly tested this?

```
% mapt aws fedora create --spot --arch arm64 --backed-url file:///Users/anath/workspace --project-name mapt-aws-fedora-amd64
```
i was not passing the `--conn-details-output` flag and seems that is the cause of the error, i tried the above command and added this flag. then didn't get the error

**Review by anjannath — APPROVED** [review]

**Pull request merged**
